name = "collabblocks-edge"
main = "src/index.ts"
compatibility_date = "2023-05-18"

# Define the Durable Object for room management
[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

# Create a migration for the Durable Object
[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

# Local development with Miniflare
[miniflare]
durable_objects_persist = "./.wrangler/state" 